---
driver:
  name: vagrant
  http_proxy: 
  https_proxy: 

provisioner:
  name: chef_zero

platforms:
  # Describes a Linux host, remove if unneeded
  - name: Linux
    driver:
      box: bento/centos-7.2

  # Describes a Windows host, remove if unneeded
  - name: Windows
    driver:
      box: mwrock/Windows2012R2
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[vagrant-template::default]
    attributes:
